site_name: cppStb

theme:
  name: material

  features:
    - content.code.copy

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - files:
      - /util_stb.hpp: vmdoc/util_stb.hpp_eaf7b9.txt
  - Home: index.md
  - vmdoc: vmdoc/vmdocs.md
markdown_extensions:
  - codehilite:
      guess_lang: false # Ensures correct language highlighting
  - fenced_code
  - pymdownx.superfences
  - pymdownx.tabbed
  - attr_list
